
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    name: sign
    url: jdbc:mysql://1.116.75.147:3306/sign?characterEncoding=utf8&useUnicode=true&characterSetResults=utf8
    username: root
    password: mm36550332
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean